# Generated by Django 2.1.5 on 2019-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default='Null')),
                ('word', models.TextField(default=None, max_length=15)),
                ('translate', models.TextField(default=None, max_length=30)),
                ('iteration', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('last_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(default=None, max_length=15)),
                ('translate', models.TextField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('name_current_file', models.TextField(default='')),
                ('max_inputs_number', models.IntegerField(default=0)),
            ],
        ),
    ]
